### ISSUE TITLE
Add Python plugin passlib

### ISSUE THREAD

**Issue by marapavelka** [linuxserver/docker-pyload-ng#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Integrated passlib plugin to make the WebshareCz account work by default.

## Current Behavior

When I add the WebshareCz account and log in, the account status is invalid and I can't use it. I see this in the log:
```
[2022-11-16 10:58:14]  INFO                pyload  ACCOUNT WebshareCz: Adding user `Tro*******`...
[2022-11-16 10:58:14]  DEBUG               pyload  ACCOUNT WebshareCz: Reached login timeout for user `Tro****`
[2022-11-16 10:58:14]  INFO                pyload  ACCOUNT WebshareCz: Login user `Tro****`...
[2022-11-16 10:58:14]  DEBUG               pyload  ACCOUNT WebshareCz: LOAD URL https://webshare.cz/api/salt/ | get={} | post={'username_or_email': 'Tro****'} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2022-11-16 10:58:14]  ERROR               pyload  ACCOUNT WebshareCz: Could not login user `Tro****` | name 'passlib' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pyload/plugins/base/account.py", line 135, in login
    self.signin(self.user, self.info["login"]["password"], self.info["data"])
  File "/usr/lib/python3.9/site-packages/pyload/plugins/accounts/WebshareCz.py", line 63, in signin
    password = hashlib.sha1(passlib.hash.md5_crypt.encrypt(password, salt=salt).encode()).hexdigest()
NameError: name 'passlib' is not defined
```
## Alternatives Considered

I have to run `pip install passlib` via the Portainer console and restart pyLoad to get the account working. But I have to do this after every container update.

**Comment by aptalca** [comment]
You can use this
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by marapavelka** [comment]
Thank you very much for the advice, it works!
