### ISSUE TITLE
[BUG] Missing bs4 module for ZippyShare plugin

### ISSUE THREAD

**Issue by anarion80** [linuxserver/docker-pyload-ng#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ZippyShare plugin does not work, complaining about missing module: bs4

### Expected Behavior

After adding z download link from ZippyShare, file should be downloaded without errors.

### Steps To Reproduce

1. Install pyLoad in docker.
2. Add a file from ZippyShare to download.

### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS
- How docker service was installed:Apt
```

### CPU architecture

x86-64

### Docker creation

```bash
Created using Ansible:


- name: Create pyLoad Docker Container
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: "pyload"
        image: "lscr.io/linuxserver/pyload-ng:latest"
        pull: true
        volumes:
          - "{{ pyload_config_directory }}:/config:rw"
          - "{{ pyload_download_directory }}:/downloads:rw"
        ports:
          - "8000:8000"
        env:
          TZ: "Europe/Warsaw"
          UID: "0"
          GID: "0"
        restart_policy: unless-stopped
        memory: "1g"
        labels:
          traefik.enable: "false"
          traefik.http.routers.pyload.rule: "Host(`{{ pyload_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.pyload.tls.certresolver: "letsencrypt"
          traefik.http.routers.pyload.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.pyload.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.pyload.loadbalancer.server.port: "8000"
```
```


### Container logs

```bash
[2023-03-17 11:39:53]  INFO                pyload  Added package Fire-pyLoad containing 1 links
[2023-03-17 11:39:53]  ERROR               pyload  Error importing ZippyshareCom: No module named 'bs4'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyload/core/managers/plugin_manager.py", line 413, in load_module
    module = __import__(
  File "/usr/lib/python3.10/site-packages/pyload/plugins/downloaders/ZippyshareCom.py", line 6, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
[2023-03-17 11:39:54]  ERROR               pyload  Error importing ZippyshareCom: No module named 'bs4'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyload/core/managers/plugin_manager.py", line 413, in load_module
    module = __import__(
  File "/usr/lib/python3.10/site-packages/pyload/plugins/downloaders/ZippyshareCom.py", line 6, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
[2023-03-17 11:39:54]  CRITICAL            pyload  'NoneType' object has no attribute 'ZippyshareCom'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyload/core/managers/thread_manager.py", line 317, in assign_job
    job.init_plugin()
  File "/usr/lib/python3.10/site-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyload/core/datatypes/pyfile.py", line 96, in init_plugin
    self.pluginclass = getattr(
AttributeError: 'NoneType' object has no attribute 'ZippyshareCom'
```

**Comment by anarion80** [comment]
Bump.

**Comment by GammaC0de** [comment]
ZippyShare is no more.
