### ISSUE TITLE
[BUG] <title>Exception: Loaded URL exceeded limit (2000000)

### ISSUE THREAD

**Issue by V-a-v-a-n** [linuxserver/docker-pyload-ng#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to download a file from the Uptobox website using version 0.5.0b3.dev73-ls90 of /linuxserver/docker-pyload-ng, an exception is thrown with the message "Loaded URL exceeded limit (2000000)". However, this error does not occur when using version 0.5.0b3.dev54-ls60 of the same project.

### Steps To Reproduce

1. Launch /linuxserver/docker-pyload-ng version 0.5.0b3.dev73-ls90.
2. Add a download link from the Uptobox site in the pyLoad interface.
3. Initiate the download of the file from Uptobox.
4. The "Loaded URL exceeded limit (2000000)" exception is generated.

### Environment

```markdown
System
Python Version:3.11.4 (main, Jun 9 2023, 02:29:05) [GCC 12.2.1 20220924]OS Platform:posix linux Linux 6842b0621177 5.10.160-rk35xx #1 SMP Fri Jul 28 02:46:55 UTC 2023 aarch64
pyLoad
Version:0.5.0Installation Folder:/lsiopy/lib/python3.11/site-packages/pyloadConfig Folder:/configLanguage:en
Docker version 24.0.5, build ced0996
```

### CPU architecture

arm64

### Docker creation

```bash
version: '3'
services:
  pyload_latest:
    container_name: pyload_latest
    image: linuxserver/pyload-ng:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/PyLoadXpress/PyloadLatest/Conf:/config
      - /home/PyLoadXpress/DownloadGalaxyLatest:/downloads
    ports:
      - 8001:8000
    networks:
      - pyload_latest_network

networks:
  pyload_latest_network:
    driver: bridge
```

### Container logs

```bash
189	2023-08-28 22:00:24	INFO	pyload	Added package sdf containing 1 links
190	2023-08-28 22:00:24	INFO	pyload	Download starts: 6o2tdh4ylgoh
191	2023-08-28 22:00:24	DEBUG	pyload	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
192	2023-08-28 22:00:24	DEBUG	pyload	ADDON UserAgentSwitcher: Setting maximum redirections to 10
193	2023-08-28 22:00:24	DEBUG	pyload	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
194	2023-08-28 22:00:24	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_preparing`
195	2023-08-28 22:00:24	DEBUG	pyload	DOWNLOADER UptoboxCom[3]: Plugin version: 0.40
196	2023-08-28 22:00:24	DEBUG	pyload	DOWNLOADER UptoboxCom[3]: Plugin status: testing
197	2023-08-28 22:00:24	WARNING	pyload	DOWNLOADER UptoboxCom[3]: Plugin may be unstable
198	2023-08-28 22:00:24	INFO	pyload	ACCOUNT UptoboxCom: Grabbing account info for user `_Va****`...
199	2023-08-28 22:00:24	DEBUG	pyload	ACCOUNT UptoboxCom: LOAD URL https://uptobox.link/my_account | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
200	2023-08-28 22:00:24	DEBUG	pyload	ACCOUNT UptoboxCom: Account info for user `_Va****`: {'login': {'password': '**********', 'stats': [2, 1693252557.9352822], 'timestamp': 1693252557.3164186, 'valid': True}, 'data': {'login': '_Va****', 'options': {'limit_dl': ['0']}, 'plugin': <Account UptoboxCom>, 'premium': True, 'trafficleft': -1, 'type': 'UptoboxCom', 'validuntil': 1735086112.0}}
201	2023-08-28 22:00:24	DEBUG	pyload	ACCOUNT UptoboxCom: Using account _Va*******
202	2023-08-28 22:00:24	INFO	pyload	DOWNLOADER UptoboxCom[3]: Processing url: https://uptobox.com/6o2tdh4ylgoh
203	2023-08-28 22:00:24	DEBUG	pyload	DOWNLOADER UptoboxCom[3]: LOAD URL https://uptobox.link/6o2tdh4ylgoh | get={} | post={} | ref=False | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
204	2023-08-28 22:00:26	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_processed`
205	2023-08-28 22:00:26	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_processed`
206	2023-08-28 22:00:26	WARNING	pyload	Download failed: 6o2tdh4ylgoh | Loaded URL exceeded limit (2000000)
207	?	?	?	Traceback (most recent call last):
208	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/threads/download_thread.py", line 56, in run
209	?	?	?	    pyfile.plugin.preprocessing(self)
210	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
211	?	?	?	    return self._process(*args, **kwargs)
212	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
213	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 103, in _process
214	?	?	?	    self.process(self.pyfile)
215	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/simple_downloader.py", line 266, in process
216	?	?	?	    self._preload()
217	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/simple_downloader.py", line 249, in _preload
218	?	?	?	    self.data = self.load(
219	?	?	?	                ^^^^^^^^^^
220	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/hoster.py", line 506, in load
221	?	?	?	    return super().load(*args, **kwargs)
222	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
223	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/plugin.py", line 217, in load
224	?	?	?	    html = req.load(
225	?	?	?	           ^^^^^^^^^
226	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/browser.py", line 127, in load
227	?	?	?	    return self.http.load(*args, **kwargs)
228	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
229	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/http/http_request.py", line 314, in load
230	?	?	?	    raise self.exception from None
231	?	?	?	Exception: Loaded URL exceeded limit (2000000)
232	2023-08-28 22:00:26	INFO	pyload	Debug Report written to /tmp/pyLoad/debug_UptoboxCom_2023-08-28_22-00-26.zip
233	2023-08-28 22:00:26	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: 6o2tdh4ylgoh (pid:3)
234	2023-08-28 22:00:26	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
235	2023-08-28 22:00:26	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_failed`
236	2023-08-28 22:00:26	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
237	2023-08-28 22:00:26	DEBUG	pyload	All downloads processed
```

**Comment by aptalca** [comment]
Probably should be reported upstream
