### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by masterlog80** [linuxserver/docker-pyload-ng#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I am running [docker-pyload-ng](https://github.com/linuxserver/docker-pyload-ng) as 1000:1000 and it works fine, unless I need to store files to a SMB Share mounted locally. The Share is defined in the docker-compose file with correct login details for R/W, but Pyload is unable to store files there ("download failed" abd "permission denied" are shown in the logs).
The only workaround I have found is run the Container as 0:0 (root), but other containers running as 1000:1000 can definirely write to that SMB Share.
Any ideas to prevent this and run the container as 1000:1000?

Regards,

### Expected Behavior

Being able to write to a SMB Share once running the Container as 1000:1000.

### Steps To Reproduce

1. Create a SMB Share
2. Define the SMB Share on a docker compose file.
3. Spint up docker-pyload-ng Container with the SMB Share defined as Volume
4. Try downloading a file there

### Environment

```markdown
- OS: Ubuntu 22
- How docker service was installed: Per official documentation
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose -f pyload.yml up -d
```

### Container logs

```bash
943	2023-10-08 16:48:00	INFO	pyload	DOWNLOADER DefaultPlugin[11]: Processing url: https://releases.ubuntu.com/22.04.3/ubuntu-22.04.3-desktop-amd64.iso?_ga=2.248187714.474370568.1696751262-2017404422.1694774606
944	2023-10-08 16:48:00	DEBUG	pyload	DOWNLOADER DefaultPlugin[11]: DOWNLOAD URL https://releases.ubuntu.com/22.04.3/ubuntu-22.04.3-desktop-amd64.iso?_ga=2.248187714.474370568.1696751262-2017404422.1694774606 | get={} | post={} | ref=False | cookies=True | disposition=True | resume=None | chunks=None
945	2023-10-08 16:48:00	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_processed`
946	2023-10-08 16:48:00	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_processed`
947	2023-10-08 16:48:00	WARNING	pyload	Download failed: ubuntu-22.04.3-desktop-amd64.iso | [Errno 13] Permission denied: '/downloads/https___releases.ubuntu.com_22.04.3_ubuntu-22.04.3-desktop-amd64.iso__ga_2.248187714.474370568.1696751262-2017404422.1694774606'
948	?	?	?	Traceback (most recent call last):
949	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/threads/download_thread.py", line 56, in run
950	?	?	?	    pyfile.plugin.preprocessing(self)
951	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
952	?	?	?	    return self._process(*args, **kwargs)
953	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
954	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 103, in _process
955	?	?	?	    self.process(self.pyfile)
956	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/downloaders/Http.py", line 74, in process
957	?	?	?	    self.download(url, ref=False, disposition=True)
958	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 322, in download
959	?	?	?	    os.makedirs(dl_dirname, exist_ok=True)
960	?	?	?	  File "<frozen os>", line 225, in makedirs
961	?	?	?	PermissionError: [Errno 13] Permission denied: '/downloads/https___releases.ubuntu.com_22.04.3_ubuntu-22.04.3-desktop-amd64.iso__ga_2.248187714.474370568.1696751262-2017404422.1694774606'
962	2023-10-08 16:48:00	INFO	pyload	Debug Report written to /tmp/pyLoad/debug_DefaultPlugin_2023-10-08_16-48-00.zip
963	2023-10-08 16:48:00	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_failed`
964	2023-10-08 16:48:00	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: ubuntu-22.04.3-desktop-amd64.iso (pid:11)
965	2023-10-08 16:48:00	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
966	2023-10-08 16:48:01	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
967	2023-10-08 16:48:01	DEBUG	pyload	All downloads processed
```

**Comment by drizuid** [comment]
We do not offer support for making remote mounts work. I would suggest testing with local storage to rule out a container problem. If local (linux filesystem) storage works, this is not a container problem. Open a new ghi with the full template filled out in the case you still have issues with local storage.
