### ISSUE TITLE
[BUG] Unable to use Ddownload

### ISSUE THREAD

**Issue by the-unknown** [linuxserver/docker-pyload-ng#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to add my ddownload account, the account is shown as " not valid".
Looking at the logs, it shows `Could not resolve host: ddownload.com`

### Expected Behavior

Account should work without an issue

### Steps To Reproduce

1. Setup a Raspberry Pi with Rasberry Pi OS
2. Install Docker incl. docker compose
3. Get docker compose file content from from README
4. run the server

### Environment

```markdown
- OS:Rasberry Pi OS (Debian 12) aarch64
- How docker service was installed:
Using this tutorial: https://docs.docker.com/engine/install/debian/
```

### CPU architecture

arm64

### Docker creation

```bash
---
version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /media/terrastore/downloads:/downloads
    ports:
      - 8000:8000
      - 9666:9666 #optional
    restart: unless-stopped
```
```


### Container logs

```bash
392	2023-12-27 14:13:43	INFO	pyload	ACCOUNT DdownloadCom: Adding user `ksu*******`...
393	2023-12-27 14:13:43	DEBUG	pyload	ACCOUNT DdownloadCom: Reached login timeout for user `ksu****`
394	2023-12-27 14:13:43	INFO	pyload	ACCOUNT DdownloadCom: Login user `ksu****`...
395	2023-12-27 14:13:43	DEBUG	pyload	ACCOUNT DdownloadCom: LOAD URL http://ddownload.com/login.html | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
396	2023-12-27 14:13:48	ERROR	pyload	ACCOUNT DdownloadCom: Could not login user `ksu****` | (6, 'Could not resolve host: ddownload.com')
397	? 	?	?	Traceback (most recent call last):
398	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/account.py", line 138, in login
399	? 	?	?	    self.signin(self.user, self.info["login"]["password"], self.info["data"])
400	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/xfs_account.py", line 188, in signin
401	? 	?	?	    self.data = self.load(self.LOGIN_URL, cookies=self.COOKIES)
402	? 	?	?	                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
403	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/plugin.py", line 217, in load
404	? 	?	?	    html = req.load(
405	? 	?	?	           ^^^^^^^^^
406	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/browser.py", line 127, in load
407	? 	?	?	    return self.http.load(*args, **kwargs)
408	? 	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
409	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/http/http_request.py", line 311, in load
410	? 	?	?	    self.c.perform()
411	? 	?	?	pycurl.error: (6, 'Could not resolve host: ddownload.com')
```
```

**Comment by j0nnymoe** [comment]
`Could not resolve host: ddownload.com`

This is an issue with your networking, not with the container. Make sure your host can resolve that host first.

**Comment by the-unknown** [comment]
sorry, my bad!
You where right.
I added `network_mode: 'host'` to my docker-compose and now it works!

**Comment by j0nnymoe** [comment]
That's probably not the correct solution but at least it proves that it's not the container at fault :)
