### ISSUE TITLE
[BUG] 'SSL certificate problem: unable to get local issuer certificate'

### ISSUE THREAD

**Issue by the-unknown** [linuxserver/docker-pyload-ng#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Downloads won't start, because of the follwing error message:
`'SSL certificate problem: unable to get local issuer certificate'`

### Expected Behavior

Downloads start as usual

### Steps To Reproduce

1.     Setup a Raspberry Pi with Rasberry Pi OS
2.     Install Docker incl. docker compose
3.     Get docker compose file content from from README
4.     run the server

### Environment

```markdown
- OS:Rasberry Pi OS (Debian 12) aarch64
- How docker service was installed:
Using this tutorial: https://docs.docker.com/engine/install/debian/
```

### CPU architecture

arm64

### Docker creation

```bash
version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /media/terrastore/downloads:/downloads
    restart: unless-stopped
```

### Container logs

```bash
5454	2024-01-06 15:55:15	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_processed`
5455	2024-01-06 15:55:15	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_processed`
5456	2024-01-06 15:55:15	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `package_failed`
5457	2024-01-06 15:55:15	WARNING	pyload	Download failed: d3b1a486-33c6-4801-a013-b3cad29b8e79.part12.rar | (60, 'SSL certificate problem: unable to get local issuer certificate')
5458	? 	?	?	Traceback (most recent call last):
5459	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/threads/download_thread.py", line 55, in run
5460	? 	?	?	    pyfile.plugin.preprocessing(self)
5461	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
5462	? 	?	?	    return self._process(*args, **kwargs)
5463	? 	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
5464	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 103, in _process
5465	? 	?	?	    self.process(self.pyfile)
5466	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/simple_downloader.py", line 286, in process
5467	? 	?	?	    self.download(self.link, disposition=self.DISPOSITION)
5468	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 330, in download
5469	? 	?	?	    newname = self._download(
5470	? 	?	?	              ^^^^^^^^^^^^^^^
5471	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 238, in _download
5472	? 	?	?	    newname = self.req.http_download(
5473	? 	?	?	              ^^^^^^^^^^^^^^^^^^^^^^^
5474	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/browser.py", line 116, in http_download
5475	? 	?	?	    name = self.dl.download(chunks, resume)
5476	? 	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
5477	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/http/http_download.py", line 132, in download
5478	? 	?	?	    self._download(chunks, resume)
5479	? 	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/http/http_download.py", line 275, in _download
5480	? 	?	?	    raise ex or Exception
5481	? 	?	?	pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')
5482	2024-01-06 15:55:15	INFO	pyload	Debug Report written to /tmp/pyLoad/debug_DdownloadCom_2024-01-06_15-55-15.zip
5483	2024-01-06 15:55:15	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `download_failed`
5484	2024-01-06 15:55:15	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: d3b1a486-33c6-4801-a013-b3cad29b8e79.part12.rar (pid:3)
5485	2024-01-06 15:55:15	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
5486	2024-01-06 15:55:15	DEBUG	pyload	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
5487	2024-01-06 15:55:15	DEBUG	pyload	All downloads processed
```

**Comment by the-unknown** [comment]
You might want to take a look at:
https://gitlab.com/dedyms/pyload-ng

There the downloads work, without an SSL error (although I can't use it, as it seems not to support a persistent config)

**Comment by duderinio247** [comment]
I had the same problem and was able to solve it by adding the corresponding certificates.

The procedure is described here:
https://github.com/pyload/pyload/issues/4273#issuecomment-1539164273

and the certificate can be downloaded here
https://support.globalsign.com/ca-certificates/intermediate-certificates/alphassl-intermediate-certificates

I have added both certificates to the cacert.pem file and it works for me now.
