### ISSUE TITLE
[BUG]  rapidgator.net DNS issues

### ISSUE THREAD

**Issue by marc-cenon** [linuxserver/docker-pyload-ng#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

seems i can't contact rapidgator.net from within the container but other sites works. For example from within the container with the curl command

`curl rapidgator.net
curl: (7) Failed to connect to rapidgator.net port 80 after 43 ms: Could not connect to server`

It is not a account error but a dns error. rapidgator.net is not resolving but all others are.

### Expected Behavior

successfull login

### Steps To Reproduce

1- install with docker
2 - login in the webui and enter login and password for premium account

### Environment

```markdown
- OS: ubuntu server / k8s
- How docker service was installed: using bas image for deployment with service and pvc
```

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
LOAD URL https://rapidgator.net/api/user/login | get={'username': '*******', 'password': '**********'} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2024-12-07 20:20:55]  ERROR               pyload  ACCOUNT RapidgatorNet: (7, 'Failed to connect to rapidgator.net port 443 after 20 ms: Could not connect to server')
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/accounts/RapidgatorNet.py", line 58, in signin
    json_data = self.api_request("login", username=user, password=password)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/accounts/RapidgatorNet.py", line 26, in api_request
    json_data = self.load(self.API_URL + method, get=kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/plugin.py", line 217, in load
    html = req.load(
           ^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/browser.py", line 128, in load
    return self.http.load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/http/http_request.py", line 317, in load
    self.c.perform()
pycurl.error: (7, 'Failed to connect to rapidgator.net port 443 after 20 ms: Could not connect to server')
[2024-12-07 20:20:55]  ERROR               pyload  ACCOUNT RapidgatorNet: Could not login user `*******` | Login handshake has failed
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/account.py", line 138, in login
    self.signin(self.user, self.info["login"]["password"], self.info["data"])
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/accounts/RapidgatorNet.py", line 80, in signin
    self.fail_login()
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/account.py", line 498, in fail_login
    return self.fail(msg)
           ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/plugin.py", line 154, in fail
    raise Fail(msg)
pyload.core.network.exceptions.Fail: Login handshake has failed
```

**Comment by j0nnymoe** [comment]
If you're having issues with specific hosts and other ones are working fine, this will be a local DNS issue to your host/connection - not something specific to the container.
